on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches:
      - main
      - develop
name: Build Code
env:
  # the name of the repo
  HOME_REPO: usnistgov/liboscal-java
  HOME_BRANCH_RELEASE: main
  HOME_BRANCH_DEVELOPMENT: develop
  # paths
  REPO_PATH: git-content/liboscal-java
jobs:
  build-artifacts:
    name: Build and Test Java Artifacts
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.REPO_PATH }}
          submodules: recursive
      # -------------------------
      # Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      # -------------------------
      # Maven Build
      - name: Build and run tests
        run: |
          mvn -Prelease verify
        working-directory: ${{ env.REPO_PATH }}
      - name: Gathering JAR files
        run: |
          mkdir staging
          find . -path "*/target/*.jar" -exec cp {} ./staging/ \;
        working-directory: ${{ env.REPO_PATH }}
      - name: Saving built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
