on:
  push:
    tags:
      - "v*"
name: Deploy Tagged Release
env:
  # the name of the repo
  HOME_REPO: usnistgov/liboscal-java
  HOME_BRANCH_RELEASE: main
  HOME_BRANCH_DEVELOPMENT: develop
  # paths
  REPO_PATH: git-content/liboscal-java
jobs:
  deploy-to-nexus:
    name: Build and Publish Java Artifacts
    runs-on: ubuntu-18.04
    steps:
      # use this for main repo builds
      - uses: actions/checkout@v2
        with:
          path: ${{ env.REPO_PATH }}
          submodules: recursive
      # -------------------------
      # Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      # -------------------------
      # Maven Deploy
      - name: Deploy Maven Artifacts
        run: |
            mvn -Pgpg -Prelease deploy
            # mvn -Pgpg -Prelease nexus-staging:close -DstagingDescription="closing to release"
        working-directory: ${{ env.REPO_PATH }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
